### Get all persons
GET http://localhost:3001/api/persons

### API info
GET http://localhost:3001/api/info

### Get a person with id valid
GET http://localhost:3001/api/persons/2

### Get a person with id invalid
GET http://localhost:3001/api/persons/a

### Delete a person
DELETE http://localhost:3001/api/persons/2

### Add a new person
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Pedro testeos",
  "number": "123123"
}

### Wrong name validation test
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "person": "Pedro testeos",
  "number": "123123"
}
