### Get all persons
GET https://phonebook-backend-pnn6.onrender.com/api/persons

### API info
GET https://phonebook-backend-pnn6.onrender.com/api/info

### Get a person with id valid
GET https://phonebook-backend-pnn6.onrender.com/api/persons/2

### Get a person with id invalid
GET https://phonebook-backend-pnn6.onrender.com/api/persons/a

### Delete a person
DELETE https://phonebook-backend-pnn6.onrender.com/api/persons/2

### Add a new person
POST https://phonebook-backend-pnn6.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Pedro testeos",
  "number": "123123"
}

### Wrong name validation test
POST https://phonebook-backend-pnn6.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
  "person": "Pedro testeos",
  "number": "123123"
}
